server {
    listen 8081;
    server_name _;

    root /home/ubuntu/projetflutter/frontend/build/web;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
}
